version: '3.8'

services:
  app:
    build: .
    container_name: chess-game
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
